version: '3'
services:
  sonardb:
    image: mysql
    volumes:
      - "/data/sonarqube/mysql:/var/lib/mysql"  
    environment:
      MYSQL_ROOT_PASSWORD: [your db password] 
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - "/data/sonarqube/logs:/usr/local/sonarqube/logs"     
    links：
      - sonardb
    depends_on:
      - sonardb
   